### ISSUE TITLE
Type Check

### ISSUE THREAD

**Issue by yasintz** [pass-wall/passwall-web#21]
There should be type check in the application.
I think typescript.

**Comment by yakuter** [comment]
I agree with this idea. What do you think @ademilter?

**Comment by yakuter** [comment]
@yasintz I think if we want to be good at this project, we must convert project to typescript. Do you mind working on it?

**Comment by yasintz** [comment]
Yeah. I think to start when the task related to the main page is over.

**Comment by yasintz** [comment]
you can assign to me.

**Comment by yakuter** [comment]
Thank you so much. This is great.

**Comment by yasintz** [comment]
#39

**Comment by yakuter** [comment]
Done!
