### ISSUE TITLE
Login Bug

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-web#22]
There is a bug on login. I can't login easily and I need to refresh the page after login. @yasintz do you have time to work on this?

**Comment by yasintz** [comment]
Of course.  I can send a pr today.

**Comment by yakuter** [comment]
Thank you.

**Comment by yasintz** [comment]
#23

**Comment by yakuter** [comment]
Thank you @yasintz closing the issue. Did you get my email about main page?

**Comment by yasintz** [comment]
nope

**Comment by yakuter** [comment]
Sendin again
