### ISSUE TITLE
Localhost is not a valid URL bug

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-web#27]
URL check fails on localhost. Can someone work on this?
![Screen Shot 2020-04-23 at 11 04 49](https://user-images.githubusercontent.com/3696314/80074792-6534e800-8552-11ea-9952-61304e3c1e97.png)

**Comment by akaramanapp** [comment]
Ok. I fixed bug.  #28

**Comment by akaramanapp** [comment]
@yakuter new pr #29

**Comment by yakuter** [comment]
Thank you for your help. I merged one of them and wanted review from @oguzhaninan. This bug is fixed. Closing the issue.
