### ISSUE TITLE
Should we have categories?

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-web#41]
What do you think about categories and more objects like logins? Should we have or this simple style is enough?
<img width="167" alt="Screen Shot 2020-04-25 at 02 22 35" src="https://user-images.githubusercontent.com/3696314/80264281-50fd0200-869c-11ea-8798-ad78603f956e.png">
<img width="409" alt="Screen Shot 2020-04-25 at 02 23 37" src="https://user-images.githubusercontent.com/3696314/80264282-522e2f00-869c-11ea-9028-a9a9f2afbc84.png">

**Comment by yasintz** [comment]
This feature should be developed in api first.
What do you think @yakuter

**Comment by yakuter** [comment]
Yes of course. I just wanted to get ideas

**Comment by aykutkardas** [comment]
I like to group my assets. It's a good idea for me. @yakuter

**Comment by yakuter** [comment]
@aykutkardas but these are not about grouping. In fact this is not category, this is type because the fields of the passwords change in each type.

**Comment by yakuter** [comment]
I am going to start adding categories.
