### ISSUE TITLE
no-referrer-when-downgrade problem in API requests.

### ISSUE THREAD

**Issue by aykutkardas** [pass-wall/passwall-web#53]
I am having trouble with API requests I send from my desktop computer. It works on another computer.

![image](https://user-images.githubusercontent.com/7966133/80771974-c1ed5f80-8b5d-11ea-8d3f-dda676ebcab5.png)

![image](https://user-images.githubusercontent.com/7966133/80771909-88b4ef80-8b5d-11ea-93b6-a4e2eaaf98e4.png)

**Comment by yakuter** [comment]
@aykutkardas I just changed the API endpoints a little and created this issue about the things we must change on web #55

**Comment by aykutkardas** [comment]
> @aykutkardas I just changed the API endpoints a little and created this issue about the things we must change on web #55

@yakuter The README that caused it. 

**PR:** https://github.com/pass-wall/passwall-web/pull/57
