### ISSUE TITLE
Turkish - APi DEĞİŞTİ, ACİL YARDIM :)

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-web#55]
Bu issue'yu bilerek Türkçe açtım çünkü basit ama bir iki önemli noktada acil yardımınıza ihtiyacım var.

1.  PassWall Server yani API url'lerinde değişiklik oldu. /logins/ ile başlayan tüm URL'lerin başına `api` geldi ve şöyle oldu /api/logins. Direk API'nin kodlarını gösterirsem API uçlarını daha iyi görebilirsiniz. Ayrıca dokümantasyonu da güncelledim.
![Screen Shot 2020-05-01 at 04 33 42](https://user-images.githubusercontent.com/3696314/80774197-f6b0e500-8b64-11ea-9629-b7fadd37b10f.png)

**Not:** İlk iki sıradaki GET ve POST uçlarında logins'in sonunda / olmadığına dikkat edin. Sadece /logins olacak. 

2. Tüm giden ve gelen json isimleri snake_case oldu. URL -> url, Username->username gibi.

3. En önemli değişiklik Token üretme ve kullanma tarafında. Uç ile username ve password gönderimi aynı ancak cevap olarak şu şekilde 2 farklı token dönüyorum.

> {
>     "access_token": "eyJhbGciOiJIUzI1NiIs...",  
>     "refresh_token": "eyJhbGciOiJIUzI1NiIsInR..."
> }

**access_token:** Bu token giriş için kullanılır ve kısa sürelidir. Yani 15-30 dk civarı. Böylece güvenli olmayan http bağlantılarında man in the middle saldırılarında bir saldırgan tarafından ele geçirilse bile saldırganın token'ı kullanabilmek için sadece 15 dk süresi olur. Login olmak için hep bu token'ı kullanacağız.

**refresh_token:** Bu token access_token'ın süresi dolduğunda yeni token üretmek için kullanılır ve 1-2 hafta gibi bir expire süresi vardır.

Yapılacaklar:
1. Frontend tarafında ilk girişte bu iki token da local storage'a kaydedilecek.
2. Header'da Bearer token olarak her zaman access token kullanılacak.
3. Herhangi bir uçtan 401 cevabı alındığı anda artık kullanıcı hemen girişe yönlendirilmeyecek! Önce refresh token body kısmında json olacak şekilde  /auth/refresh ucuna istek atılacak. ([şurada](https://documenter.getpostman.com/view/3658426/SzYbyHXj?version=latest#1d1ca4ac-71ff-485e-b7a6-f81a2539ff70) örnek istek var)
4. Burada yeni üretilen iki token local storage'dakilerle değiştirilecek ve yeniden access_token ile uygulamaya devam edilecek. 
5. Eğer refresh token ile yeni token üretilemezse refresh token expire olmuş demektir. İşte o zaman kullanıcı ilk giriş sayfasına yönlendirilecek.

Müsait olan bir arkadaş bu konuyla acilen ilgilenebilir mi acaba?

**Comment by aykutkardas** [comment]
> Tüm giden ve gelen json isimleri snake_case oldu. URL -> url, Username->username gibi.

**BaseURL**  nasıl değişti?  @yakuter 

`base_url`  ya da `base_URL`

**Comment by aykutkardas** [comment]
> En önemli değişiklik Token üretme ve kullanma tarafında. Uç ile username ve password gönderimi aynı ancak cevap olarak şu şekilde 2 farklı token dönüyorum.

```
Request URL: https://passwall-web.herokuapp.com/auth/signin
Referrer Policy: no-referrer-when-downgrade
```

CORS dan dolayı test edemiyorum. @yakuter

**Comment by yakuter** [comment]
@aykutkardas I can get response from server via browaser?
![Screen Shot 2020-05-01 at 09 49 22](https://user-images.githubusercontent.com/3696314/80788246-43121a00-8b91-11ea-98f6-485af9ba9519.png)

**Comment by aykutkardas** [comment]
Sorun buradaki giriş bilgilerini form alanları ile eşleştirmemmiş. Doküman benim için yanıltıcı oldu. passwall-server  yerine passwall-web e istek atıyormuşum.

![image](https://user-images.githubusercontent.com/7966133/80796809-d86cd880-8ba8-11ea-9025-3922de5d82cf.png)

**Comment by aykutkardas** [comment]
> @aykutkardas ben browserdan istek attığımda cevap alabiliyorum?
> ![Screen Shot 2020-05-01 at 09 49 22](https://user-images.githubusercontent.com/3696314/80788246-43121a00-8b91-11ea-98f6-485af9ba9519.png)

@yakuter Doküman benim için yanıltıcı oldu. passwall-server yerine passwall-web e istek atıyormuşum. Bu karışıklık ile ilgili bir PR attım.

**PR:** #57

**Comment by yakuter** [comment]
Teşekkür ederim. Merge yaptım.

**Comment by cyberst** [comment]
> 
> Yapılacaklar:
> 
> 1. Frontend tarafında ilk girişte bu iki token da local storage'a kaydedilecek.
> 2. Header'da Bearer token olarak her zaman access token kullanılacak.
> 3. Herhangi bir uçtan 401 cevabı alındığı anda artık kullanıcı hemen girişe yönlendirilmeyecek! Önce refresh token body kısmında json olacak şekilde  /auth/refresh ucuna istek atılacak. ([şurada](https://documenter.getpostman.com/view/3658426/SzYbyHXj?version=latest#1d1ca4ac-71ff-485e-b7a6-f81a2539ff70) örnek istek var)
> 4. Burada yeni üretilen iki token local storage'dakilerle değiştirilecek ve yeniden access_token ile uygulamaya devam edilecek.
> 5. Eğer refresh token ile yeni token üretilemezse refresh token expire olmuş demektir. İşte o zaman kullanıcı ilk giriş sayfasına yönlendirilecek.
> 
> Müsait olan bir arkadaş bu konuyla acilen ilgilenebilir mi acaba?

Bu 5 maddeden hangileri kaldı acaba en son?

**Comment by yakuter** [comment]
1 ve 2'yi ben yaptım. 3-4-5 için status code'un json objesinde dönülmesine ihtiyaç olduğunu iletti @aykutkardas. Şimdi onu da ekledim ve @aykutkardas çalışmaya başladı. Sanırım onun dışında bu ihtiyaçları şimdilik çözmüş oluyoruz.

@cyberst müsaitsen #60 konusunda destek iyi olurdu :)

**Comment by cyberst** [comment]
Tamamdır #60 ile ilgilenmeye çalışayım ben :)

**Comment by yakuter** [comment]
All the issues are finished. Thank you all.
