### ISSUE TITLE
Restore feature does not work.

### ISSUE THREAD

**Issue by aykutkardas** [pass-wall/passwall-web#58]
Request URL: https://passwall-server.herokuapp.com/api/logins/restore
Request Method: POST
Status Code: 404 Not Found

Maybe there may be a problem on the path. *(double slash)*

```sh
./store//passwall.bak
```
![image](https://user-images.githubusercontent.com/7966133/80798689-a14cf600-8bad-11ea-935d-bc811130ffc1.png)

**Comment by yakuter** [comment]
There is an enhancement in server for backup. So we need to update backup system as explained here: #60
