### ISSUE TITLE
Update Backup and Restore needed

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-web#60]
Our backup system was so simple. Now thanks to our beloved contributors we have a more advanced backup structure. The server backups automatically in a time interval. Also our POST backup endpoint still works for manual triggering. 

On the other side for frontend there is 2 things to do. First send a GET request to /api/logins/backup to get the list of available file names and backup dates as in the picture.
<img width="482" alt="Screen Shot 2020-05-01 at 14 16 10" src="https://user-images.githubusercontent.com/3696314/80802496-29d09400-8bb8-11ea-83b1-5dd84684fc92.png">

Then user shoud select one of the backup file and make a POST request to /api/logins/restore endpoint with filename in body with json format as in the picture.
<img width="628" alt="Screen Shot 2020-05-01 at 14 30 41" src="https://user-images.githubusercontent.com/3696314/80802596-6b613f00-8bb8-11ea-93c8-b756dcab0d26.png">

Can I assign this job to a volunteer who wants to do this job?

**Comment by cyberst** [comment]
I can get assigned to this issue

**Comment by yakuter** [comment]
Thank you. I assigned it now.
